// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities
{

    public partial class Order
    {
        public short OrderId { get; set; }

        public DateOnly? OrderDate { get; set; }

        public short OrderSum { get; set; }

        public short UserId { get; set; }

        public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();

        public virtual User User { get; set; }
    }
}