// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities
{

    public partial class OrdersItem
    {
        public short OrderItemId { get; set; }

        public short ProductsId { get; set; }

        public short OrderId { get; set; }

        public short Quantity { get; set; }

        public virtual Order Order { get; set; }

        public virtual Product Products { get; set; }
    }
}