// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities
{

    public partial class Product
    {
        public short ProductsId { get; set; }

        public short CategoryId { get; set; }

        public string ProductsName { get; set; }

        public string ProductsDescreption { get; set; }

        public double Price { get; set; }

        public string ImgUrl { get; set; }

        public virtual Category Category { get; set; }

        public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
    }
}